{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5d746fe5-1faf-46eb-84ec-b9faf4691a9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ app.py has been created with Piyasee Khokhar as the website author.\n",
      "Launching Streamlit app...\n",
      "🌐 Open in your browser: http://localhost:8501\n",
      "⏳ Press Ctrl+C in the terminal to stop the server when done.\n"
     ]
    }
   ],
   "source": [
    "# =============================================================================\n",
    "# CdSe Quantum Dot Calculator – Jupyter Launcher (No Unicode Errors)\n",
    "# Website Title: Piyasee Khokhar\n",
    "# =============================================================================\n",
    "import subprocess\n",
    "import sys\n",
    "import time\n",
    "import webbrowser\n",
    "import os\n",
    "\n",
    "# Step 1: Install streamlit if not present\n",
    "try:\n",
    "    import streamlit\n",
    "except ImportError:\n",
    "    print(\"Installing streamlit...\")\n",
    "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"streamlit\"])\n",
    "    print(\"Streamlit installed.\")\n",
    "\n",
    "# Step 2: Write the complete app.py file (ASCII only)\n",
    "app_code = '''#!/usr/bin/env python3\n",
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "\"\"\"\n",
    "CdSe Quantum Dot Calculator – Interactive Dashboard (Complete)\n",
    "Website: Piyasee Khokhar\n",
    "\"\"\"\n",
    "\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ============================================================================\n",
    "# 1. CONSTANTS & CORE FUNCTIONS\n",
    "# ============================================================================\n",
    "E_g_bulk = 1.74\n",
    "me_star = 0.13\n",
    "mh_star = 0.45\n",
    "eps_r = 9.5\n",
    "a_B = 5.6\n",
    "CBM_bulk = -4.95\n",
    "VBM_bulk = -6.69\n",
    "A_conf = 3.729\n",
    "B_coul = 0.2707\n",
    "\n",
    "def band_gap(R):\n",
    "    return E_g_bulk + A_conf / R**2 - B_coul / R\n",
    "\n",
    "def cbm(R):\n",
    "    delta_Eg = band_gap(R) - E_g_bulk\n",
    "    delta_Ec = (mh_star / (me_star + mh_star)) * delta_Eg\n",
    "    return CBM_bulk + delta_Ec\n",
    "\n",
    "def vbm(R):\n",
    "    delta_Eg = band_gap(R) - E_g_bulk\n",
    "    delta_Ev = (me_star / (me_star + mh_star)) * delta_Eg\n",
    "    return VBM_bulk - delta_Ev\n",
    "\n",
    "def absorption_edge(R):\n",
    "    return 1240 / band_gap(R)\n",
    "\n",
    "def blue_shift(R):\n",
    "    lambda_bulk = 1240 / E_g_bulk\n",
    "    return lambda_bulk - absorption_edge(R)\n",
    "\n",
    "def surface_fraction(R):\n",
    "    d_atom = 0.43\n",
    "    return min(1.0, 3 * d_atom / R)\n",
    "\n",
    "def volume(R):\n",
    "    return (4/3) * np.pi * R**3\n",
    "\n",
    "def surface_area(R):\n",
    "    return 4 * np.pi * R**2\n",
    "\n",
    "def sv_ratio(R):\n",
    "    return 3 / R\n",
    "\n",
    "def exciton_ratio(R):\n",
    "    return R / a_B\n",
    "\n",
    "def regime(R):\n",
    "    ratio = R / a_B\n",
    "    if ratio < 1:\n",
    "        return \"Strong\"\n",
    "    elif ratio <= 1.1:\n",
    "        return \"Intermediate\"\n",
    "    else:\n",
    "        return \"Weak\"\n",
    "\n",
    "def number_of_formula_units(R):\n",
    "    rho = 5.81\n",
    "    M = 191.37\n",
    "    NA = 6.02214076e23\n",
    "    V_cm3 = volume(R) * 1e-21\n",
    "    return int((V_cm3 * rho * NA) / M)\n",
    "\n",
    "def total_atom_count(R):\n",
    "    return 2 * number_of_formula_units(R)\n",
    "\n",
    "def confinement_energy(R):\n",
    "    return A_conf / R**2\n",
    "\n",
    "def coulomb_energy(R):\n",
    "    return B_coul / R\n",
    "\n",
    "# ============================================================================\n",
    "# 2. EXPERIMENTAL DATA\n",
    "# ============================================================================\n",
    "exp_data = [\n",
    "    (2.0, 2.40, \"Murray et al. 1993\"),\n",
    "    (2.3, 2.20, \"Peng et al. 1997\"),\n",
    "    (2.8, 2.02, \"Murray et al. 1993\"),\n",
    "    (3.0, 2.00, \"Norris & Bawendi 1996\"),\n",
    "    (3.5, 1.95, \"Norris & Bawendi 1996\"),\n",
    "    (4.0, 1.90, \"Murray et al. 1993\"),\n",
    "    (5.0, 1.83, \"Peng et al. 1997\"),\n",
    "    (6.0, 1.79, \"Norris & Bawendi 1996\"),\n",
    "    (8.0, 1.76, \"Murray et al. 1993\"),\n",
    "    (10.0, 1.74, \"NSM Archive (bulk)\")\n",
    "]\n",
    "exp_R = np.array([d[0] for d in exp_data])\n",
    "exp_Eg = np.array([d[1] for d in exp_data])\n",
    "\n",
    "# ============================================================================\n",
    "# 3. PLOTTING FUNCTIONS (all 21 graphs)\n",
    "# ============================================================================\n",
    "def plot_sv(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, 3/R_plot, 'b-', linewidth=2)\n",
    "    ax.scatter(R, 3/R, color='red', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"S/V (nm-1)\")\n",
    "    ax.set_title(\"1. Surface-to-Volume Ratio\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_atoms(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    atoms = [number_of_formula_units(r) for r in R_plot]\n",
    "    ax.plot(R_plot, atoms, 'g-', linewidth=2)\n",
    "    ax.scatter(R, number_of_formula_units(R), color='red', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"CdSe Units\")\n",
    "    ax.set_title(\"2. Number of CdSe Units\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_surf_frac(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    sf = [surface_fraction(r) for r in R_plot]\n",
    "    ax.plot(R_plot, sf, 'r-', linewidth=2)\n",
    "    ax.scatter(R, surface_fraction(R), color='blue', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Surface Fraction\")\n",
    "    ax.set_title(\"3. Surface Atom Fraction\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_conf(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, confinement_energy(R_plot), 'purple', linewidth=2)\n",
    "    ax.scatter(R, confinement_energy(R), color='orange', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"E_conf (eV)\")\n",
    "    ax.set_title(\"4. Confinement Energy\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_coul(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, coulomb_energy(R_plot), 'orange', linewidth=2)\n",
    "    ax.scatter(R, coulomb_energy(R), color='purple', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"E_coul (eV)\")\n",
    "    ax.set_title(\"5. Coulomb Energy\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_bandgap_exp(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    Eg_plot = [band_gap(r) for r in R_plot]\n",
    "    ax.plot(R_plot, Eg_plot, 'b-', linewidth=2, label='Brus model')\n",
    "    ax.scatter(exp_R, exp_Eg, color='red', marker='x', s=80, label='Experimental')\n",
    "    ax.scatter(R, band_gap(R), color='green', marker='o', s=120, label=f'R={R:.1f} nm', zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Band Gap (eV)\")\n",
    "    ax.set_title(\"6. Size-Dependent Band Gap\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_shift(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, [band_gap(r)-E_g_bulk for r in R_plot], 'brown', linewidth=2)\n",
    "    ax.scatter(R, band_gap(R)-E_g_bulk, color='green', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Delta Eg (eV)\")\n",
    "    ax.set_title(\"7. Band Gap Widening\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_cbm_vbm(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, [cbm(r) for r in R_plot], 'b-', label='CBM')\n",
    "    ax.plot(R_plot, [vbm(r) for r in R_plot], 'r-', label='VBM')\n",
    "    ax.scatter(R, cbm(R), color='blue', s=80); ax.scatter(R, vbm(R), color='red', s=80)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Energy (eV) – Vacuum=0\")\n",
    "    ax.set_title(\"8. CBM and VBM\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_rab(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, [r/a_B for r in R_plot], 'darkcyan', linewidth=2)\n",
    "    ax.axhline(y=1, color='k', linestyle='--', label='R/aB=1')\n",
    "    ax.scatter(R, exciton_ratio(R), color='magenta', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"R/aB\")\n",
    "    ax.set_title(\"9. Exciton Confinement Ratio\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_abs_edge(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, [absorption_edge(r) for r in R_plot], 'm-', linewidth=2)\n",
    "    ax.scatter(R, absorption_edge(R), color='cyan', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Absorption Edge (nm)\")\n",
    "    ax.set_title(\"10. Absorption Edge\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_blue_shift(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, [blue_shift(r) for r in R_plot], 'olive', linewidth=2)\n",
    "    ax.scatter(R, blue_shift(R), color='brown', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Blue Shift (nm)\")\n",
    "    ax.set_title(\"11. Blue Shift\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_delta_shifts(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    dEc = [(mh_star/(me_star+mh_star))*(band_gap(r)-E_g_bulk) for r in R_plot]\n",
    "    dEv = [(me_star/(me_star+mh_star))*(band_gap(r)-E_g_bulk) for r in R_plot]\n",
    "    ax.plot(R_plot, dEc, 'b-', label='Delta Ec')\n",
    "    ax.plot(R_plot, dEv, 'orange', label='Delta Ev')\n",
    "    ax.scatter(R, (mh_star/(me_star+mh_star))*(band_gap(R)-E_g_bulk), color='blue', s=80)\n",
    "    ax.scatter(R, (me_star/(me_star+mh_star))*(band_gap(R)-E_g_bulk), color='orange', s=80)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Energy Shift (eV)\")\n",
    "    ax.set_title(\"12. Band Edge Shifts\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_conf_vs_coul(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    ax.plot(R_plot, [confinement_energy(r) for r in R_plot], 'b-', label='Confinement')\n",
    "    ax.plot(R_plot, [coulomb_energy(r) for r in R_plot], 'r-', label='Coulomb')\n",
    "    ax.scatter(R, confinement_energy(R), color='blue', s=80)\n",
    "    ax.scatter(R, coulomb_energy(R), color='red', s=80)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Energy (eV)\")\n",
    "    ax.set_title(\"13. Confinement vs Coulomb\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_volume_atoms(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    vol = [volume(r) for r in R_plot]\n",
    "    atoms = [number_of_formula_units(r) for r in R_plot]\n",
    "    ax.plot(vol, atoms, 'g-', linewidth=2)\n",
    "    ax.scatter(volume(R), number_of_formula_units(R), color='red', s=80, zorder=5)\n",
    "    ax.set_xlabel(\"Volume (nm3)\"); ax.set_ylabel(\"CdSe Units\")\n",
    "    ax.set_title(\"14. Volume vs CdSe Units\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_energy_evo(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    cbm_vals = [cbm(r) for r in R_plot]\n",
    "    vbm_vals = [vbm(r) for r in R_plot]\n",
    "    ax.fill_between(R_plot, vbm_vals, cbm_vals, alpha=0.3, color='gray')\n",
    "    ax.plot(R_plot, cbm_vals, 'b-', label='CBM')\n",
    "    ax.plot(R_plot, vbm_vals, 'r-', label='VBM')\n",
    "    ax.scatter(R, cbm(R), color='blue', s=80)\n",
    "    ax.scatter(R, vbm(R), color='red', s=80)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Energy (eV) – Vacuum=0\")\n",
    "    ax.set_title(\"15. Energy Level Evolution\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_eg_vs_1r2(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    invR2 = 1 / R_plot**2\n",
    "    Eg_plot = [band_gap(r) for r in R_plot]\n",
    "    ax.plot(invR2, Eg_plot, 'navy', linewidth=2)\n",
    "    ax.scatter(1/R**2, band_gap(R), color='red', s=80, zorder=5)\n",
    "    coeffs = np.polyfit(invR2, Eg_plot, 1)\n",
    "    fit_line = np.polyval(coeffs, invR2)\n",
    "    ax.plot(invR2, fit_line, 'r--', label=f'Fit: Eg = {coeffs[0]:.2f}*(1/R2) + {coeffs[1]:.2f}')\n",
    "    ax.set_xlabel(\"1/R2 (nm-2)\"); ax.set_ylabel(\"Band Gap (eV)\")\n",
    "    ax.set_title(\"16. Band Gap vs 1/R2\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_bar_chart(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    sel_R = [1, 3, 5, 10]\n",
    "    cbm_sel = [cbm(r) for r in sel_R]\n",
    "    vbm_sel = [vbm(r) for r in sel_R]\n",
    "    x_pos = np.arange(len(sel_R))\n",
    "    width = 0.35\n",
    "    ax.bar(x_pos - width/2, cbm_sel, width, label='CBM', color='blue', alpha=0.7)\n",
    "    ax.bar(x_pos + width/2, vbm_sel, width, label='VBM', color='red', alpha=0.7)\n",
    "    ax.set_xticks(x_pos); ax.set_xticklabels([f\"R={r} nm\" for r in sel_R])\n",
    "    ax.set_ylabel(\"Energy (eV) – Vacuum=0\")\n",
    "    ax.set_title(\"17. CBM/VBM at Selected Radii\")\n",
    "    ax.legend(); ax.grid(axis='y', linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_validation_scatter(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    theory = [band_gap(r) for r in exp_R]\n",
    "    ax.scatter(theory, exp_Eg, color='red', s=80, label='Literature')\n",
    "    min_val = min(min(theory), min(exp_Eg))\n",
    "    max_val = max(max(theory), max(exp_Eg))\n",
    "    ax.plot([min_val, max_val], [min_val, max_val], 'k--', label='y=x')\n",
    "    for i, r in enumerate(exp_R):\n",
    "        ax.annotate(f\"{r:.1f} nm\", (theory[i], exp_Eg[i]), fontsize=8, xytext=(5,5), textcoords='offset points')\n",
    "    ax.set_xlabel(\"Theoretical Eg (eV)\"); ax.set_ylabel(\"Experimental Eg (eV)\")\n",
    "    ax.set_title(\"18. Theory vs Experiment\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_percent_error(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    theory = [band_gap(r) for r in exp_R]\n",
    "    rel_err = 100 * np.abs(np.array(theory) - exp_Eg) / exp_Eg\n",
    "    ax.bar(exp_R, rel_err, width=0.3, color='coral', edgecolor='black')\n",
    "    ax.axhline(y=5, color='r', linestyle='--', label='5% threshold')\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Relative Error (%)\")\n",
    "    ax.set_title(\"19. Percentage Error\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_error_bars(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    R_plot = np.linspace(1, 10, 100)\n",
    "    Eg_plot = [band_gap(r) for r in R_plot]\n",
    "    ax.plot(R_plot, Eg_plot, 'b-', linewidth=2, label='Brus')\n",
    "    ax.errorbar(exp_R, exp_Eg, yerr=0.03, fmt='rx', capsize=4, label='Experimental')\n",
    "    ax.scatter(R, band_gap(R), color='green', s=80, label=f'Selected R={R:.1f} nm')\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Band Gap (eV)\")\n",
    "    ax.set_title(\"20. Comparison with Error Bars\")\n",
    "    ax.legend(); ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "def plot_residuals(R):\n",
    "    fig, ax = plt.subplots(figsize=(6,4))\n",
    "    res = [band_gap(r) - exp_Eg[i] for i, r in enumerate(exp_R)]\n",
    "    ax.axhline(y=0, color='k', linestyle='-', linewidth=0.8)\n",
    "    ax.bar(exp_R, res, width=0.3, color='green', alpha=0.7)\n",
    "    ax.set_xlabel(\"Radius (nm)\"); ax.set_ylabel(\"Residual (eV)\")\n",
    "    ax.set_title(\"21. Residual Plot\")\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    return fig\n",
    "\n",
    "# ============================================================================\n",
    "# 4. STREAMLIT LAYOUT\n",
    "# ============================================================================\n",
    "st.set_page_config(page_title=\"Piyasee Khokhar\", layout=\"wide\")\n",
    "st.title(\"CdSe Quantum Dot Calculator\")\n",
    "st.markdown(\"**Piyasee Khokhar | GC University Hyderabad**\")\n",
    "st.markdown(\"**Interactive dashboard for size-dependent properties**\")\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# Sidebar\n",
    "with st.sidebar:\n",
    "    st.header(\"Input\")\n",
    "    R = st.slider(\"Quantum Dot Radius (nm)\", 1.0, 10.0, 3.0, 0.1)\n",
    "    st.markdown(\"---\")\n",
    "    st.header(\"Material Constants\")\n",
    "    st.write(f\"**Bulk Eg:** {E_g_bulk} eV\")\n",
    "    st.write(f\"**me*:** {me_star} m0\")\n",
    "    st.write(f\"**mh*:** {mh_star} m0\")\n",
    "    st.write(f\"**eps_r:** {eps_r}\")\n",
    "    st.write(f\"**a_B:** {a_B} nm\")\n",
    "    st.write(f\"**CBM(bulk):** {CBM_bulk} eV\")\n",
    "    st.write(f\"**VBM(bulk):** {VBM_bulk} eV\")\n",
    "\n",
    "# Top metrics\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "with col1:\n",
    "    st.metric(\"Band Gap (Eg)\", f\"{band_gap(R):.4f} eV\")\n",
    "with col2:\n",
    "    st.metric(\"CBM\", f\"{cbm(R):.2f} eV\")\n",
    "with col3:\n",
    "    st.metric(\"VBM\", f\"{vbm(R):.2f} eV\")\n",
    "with col4:\n",
    "    st.metric(\"Absorption Edge\", f\"{absorption_edge(R):.1f} nm\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "with st.expander(\"Full Parameter List\", expanded=True):\n",
    "    cols = st.columns(3)\n",
    "    params = {\n",
    "        \"Radius\": f\"{R:.1f} nm\",\n",
    "        \"Confinement Energy\": f\"{confinement_energy(R):.4f} eV\",\n",
    "        \"Coulomb Energy\": f\"{coulomb_energy(R):.4f} eV\",\n",
    "        \"Blue Shift\": f\"{blue_shift(R):.1f} nm\",\n",
    "        \"Surface Fraction\": f\"{surface_fraction(R):.2f}\",\n",
    "        \"Volume\": f\"{volume(R):.1f} nm3\",\n",
    "        \"Surface Area\": f\"{surface_area(R):.1f} nm2\",\n",
    "        \"S/V Ratio\": f\"{sv_ratio(R):.3f} nm-1\",\n",
    "        \"CdSe Units\": f\"{number_of_formula_units(R)}\",\n",
    "        \"Total Atoms\": f\"{total_atom_count(R)}\",\n",
    "        \"R/aB\": f\"{exciton_ratio(R):.2f}\",\n",
    "        \"Regime\": regime(R)\n",
    "    }\n",
    "    for i, (key, val) in enumerate(params.items()):\n",
    "        cols[i % 3].metric(key, val)\n",
    "\n",
    "st.markdown(\"---\")\n",
    "st.header(\"Graphical Analysis (21 Graphs)\")\n",
    "\n",
    "# List of all plotting functions with titles\n",
    "plot_funcs = [\n",
    "    (\"Surface-to-Volume Ratio\", plot_sv),\n",
    "    (\"Number of CdSe Units\", plot_atoms),\n",
    "    (\"Surface Atom Fraction\", plot_surf_frac),\n",
    "    (\"Confinement Energy\", plot_conf),\n",
    "    (\"Coulomb Energy\", plot_coul),\n",
    "    (\"Size-Dependent Band Gap\", plot_bandgap_exp),\n",
    "    (\"Band Gap Widening\", plot_shift),\n",
    "    (\"CBM and VBM\", plot_cbm_vbm),\n",
    "    (\"Exciton Confinement Ratio\", plot_rab),\n",
    "    (\"Absorption Edge\", plot_abs_edge),\n",
    "    (\"Blue Shift\", plot_blue_shift),\n",
    "    (\"Band Edge Shifts\", plot_delta_shifts),\n",
    "    (\"Confinement vs Coulomb\", plot_conf_vs_coul),\n",
    "    (\"Volume vs CdSe Units\", plot_volume_atoms),\n",
    "    (\"Energy Level Evolution\", plot_energy_evo),\n",
    "    (\"Band Gap vs 1/R2\", plot_eg_vs_1r2),\n",
    "    (\"CBM/VBM at Selected Radii\", plot_bar_chart),\n",
    "    (\"Theory vs Experiment\", plot_validation_scatter),\n",
    "    (\"Percentage Error\", plot_percent_error),\n",
    "    (\"Comparison with Error Bars\", plot_error_bars),\n",
    "    (\"Residual Plot\", plot_residuals)\n",
    "]\n",
    "\n",
    "# Display graphs in a grid (3 columns)\n",
    "for i in range(0, len(plot_funcs), 3):\n",
    "    cols = st.columns(3)\n",
    "    for j, (title, func) in enumerate(plot_funcs[i:i+3]):\n",
    "        with cols[j]:\n",
    "            st.pyplot(func(R))\n",
    "            plt.close()\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# Dataset table\n",
    "with st.expander(\"Complete Dataset (R = 1-10 nm)\", expanded=False):\n",
    "    radii = np.arange(1.0, 10.5, 1.0)\n",
    "    data = []\n",
    "    for r in radii:\n",
    "        data.append({\n",
    "            \"R (nm)\": r,\n",
    "            \"Eg (eV)\": band_gap(r),\n",
    "            \"CBM (eV)\": cbm(r),\n",
    "            \"VBM (eV)\": vbm(r),\n",
    "            \"lambda_edge (nm)\": absorption_edge(r),\n",
    "            \"Blue Shift (nm)\": blue_shift(r),\n",
    "            \"S/V (nm-1)\": sv_ratio(r),\n",
    "            \"Surf. Fraction\": surface_fraction(r),\n",
    "            \"Regime\": regime(r)\n",
    "        })\n",
    "    df = pd.DataFrame(data)\n",
    "    st.dataframe(df.style.format({\n",
    "        \"Eg (eV)\": \"{:.4f}\",\n",
    "        \"CBM (eV)\": \"{:.2f}\",\n",
    "        \"VBM (eV)\": \"{:.2f}\",\n",
    "        \"lambda_edge (nm)\": \"{:.1f}\",\n",
    "        \"Blue Shift (nm)\": \"{:.1f}\",\n",
    "        \"S/V (nm-1)\": \"{:.3f}\",\n",
    "        \"Surf. Fraction\": \"{:.2f}\"\n",
    "    }))\n",
    "    csv = df.to_csv(index=False)\n",
    "    st.download_button(\"Download CSV\", csv, \"CdSe_QD_dataset.csv\", \"text/csv\")\n",
    "\n",
    "st.caption(\"Piyasee Khokhar | GC University Hyderabad | All parameters verified against literature\")\n",
    "'''\n",
    "\n",
    "# Write app.py with UTF-8 encoding\n",
    "with open(\"app.py\", \"w\", encoding=\"utf-8\") as f:\n",
    "    f.write(app_code)\n",
    "\n",
    "print(\"✅ app.py has been created with Piyasee Khokhar as the website author.\")\n",
    "\n",
    "# Step 3: Launch the Streamlit app\n",
    "print(\"Launching Streamlit app...\")\n",
    "proc = subprocess.Popen([sys.executable, \"-m\", \"streamlit\", \"run\", \"app.py\",\n",
    "                         \"--server.headless\", \"true\"])\n",
    "time.sleep(5)\n",
    "webbrowser.open(\"http://localhost:8501\")\n",
    "print(\"🌐 Open in your browser: http://localhost:8501\")\n",
    "print(\"⏳ Press Ctrl+C in the terminal to stop the server when done.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01b54094-e7e1-4a2b-a55b-dd37c9bc4247",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
